development:
  indexed_models:
    - Book
  mysql41: 9334
  configuration_file: "config/development.sphinx.conf"
  log: "log/searchd.log"
  query_log: "log/searchd.query.log"
  pid_file: "log/searchd.development.pid"
  mem_limit: 128M
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  charset_type: sbcs
  charset_table: "0..9, A..Z->a..z, _, a..z, \ U+410..U+42F->U+430..U+44F, U+430..U+44F"
  max_matches: 10000
test:
  mysql41: 9313
  configuration_file: "config/testing.sphinx.conf"
  log: "log/searchd.log"
  query_log: "log/searchd.query.log"
  pid_file: "log/searchd.testing.pid"
  mem_limit: 128M
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  charset_type: sbcs
  charset_table: "0..9, A..Z->a..z, _, a..z, \ U+410..U+42F->U+430..U+44F, U+430..U+44F"
  max_matches: 10000
production:
  mysql41: 9312
  configuration_file: "config/production.sphinx.conf"
  log: "log/searchd.log"
  query_log: "log/searchd.query.log"
  pid_file: "log/searchd.production.pid"
  mem_limit: 128M
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  charset_type: sbcs
  charset_table: "0..9, A..Z->a..z, _, a..z, \ U+410..U+42F->U+430..U+44F, U+430..U+44F"
  max_matches: 10000
  quiet_deltas: true
